name: Convert Excel to HTML

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Convert Excel to HTML
      uses: peter-evans/excel-to-html@v1
      with:
        excel_file: ./sampledatainsurance.xlsx
