name: Convert Excel to HTML

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libreoffice
    - name: Convert Excel to HTML
      run: |
        libreoffice --headless --convert-to html "$GITHUB_WORKSPACE/sampledatainsurance.xlsx" --outdir "$GITHUB_WORKSPACE"
