name: Convert Excel to HTML

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Convert Excel to HTML
      uses: peter-evans/excel-to-html@v1
      with:
        excel_file: /sampledatainsurance.xlsx
      id: html
    - name: Save output HTML file
      run: |
        mkdir -p output
        echo "${{ steps.html.outputs.html }}" > output/output.html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
